### PR TITLE
Merge duplicate name of axil

### PR DESCRIPTION
**Pull request by axilleas**
Not really sure how this works. I'd like to merge http://contributors.gitlab.com/contributors/axilleas-pipinellis/commits into http://contributors.gitlab.com/contributors/achilleas-pipinellis/commits

### CODE REVIEW

**Comment by rymai** [comment]
@axilleas It think this work like that indeed! FYI, next time please open the PR at https://gitlab.com/gitlab-com/gitlab-contributors/merge_requests :)

**Comment by axilleas** [comment]
Oh, we have ported the repo? Cool!

**Comment by dosire** [comment]
@rymai can you update the readme at https://github.com/gitlabhq/gitlab-contributors with the new location?

**Comment by rymai** [comment]
@dosire Done! Also, could you give me admin access on this repo? Thanks!

**Comment by axilleas** [comment]
@rymai When you get admin access, also change the description!

**Comment by rymai** [comment]
@axilleas Yep, that's the idea!

**Pull request merged**
