### PR TITLE
add mapping for Sytse

### PR DESCRIPTION
**Pull request by bbodenmiller**

### CODE REVIEW

**Comment by rymai** [comment]
Thanks @bbodenmiller!

**Comment by dosire** [comment]
Thanks @bbodenmiller

**Comment by dosire** [comment]
@rymai I still see http://contributors.gitlab.com/contributors/dosire/commits in the list, is this working OK?

**Comment by rymai** [comment]
@dosire I didn't updated the app yet (I just fixed the issue that was causing new commits to not being added).

**Comment by axilleas** [comment]
@rymai I was wondering the same thing about my user, thanks for explaining!

**Comment by dosire** [comment]
@rymai thanks for explaining

**Comment by rymai** [comment]
Sorry about that, I will update the app ASAP and ensure I update it regularly in the future! :)

**Comment by dosire** [comment]
@rymai no problem, please let me know when it is updated

**Comment by rymai** [comment]
@axilleas @dosire I finally had time to dig into this, the changes are deployed and I will document how to manage the http://contributors.gitlab.com/ with what I could find so far!

**Comment by dosire** [comment]
@rymai thanks and thanks for documenting

**Comment by axilleas** [comment]
@rymai thanks, I can confirm this worked :)

**Comment by rymai** [comment]
You're welcome!

**Pull request merged**
